CHROME_DRIVER_PATH = "C:/Users/timab/Downloads/chromedriver-win64/chromedriver.exe"  # path to chromedriver
TESSERACT_PATH = "C:/Program Files/Tesseract-OCR/tesseract.exe"  # path to tesseract
OUTPUT_FILE_DIRECTORY = "../temp/output/"
CHROME_DIRECTORY = "C:\\Users\\timab\\PycharmProjects\\webscrapper\\dependencies\\selenium_chrome"
CHROME_PROFILE = "Profile 1"
WINDOW_W_MIN = 400
WINDOW_W_MAX = 1920
WINDOW_H_MIN = 400
WINDOW_H_MAX = 2000
